const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8');

test('learning path links unlocked stages into lesson route',()=>{const source=read('public/learning-path-ui.js');assert.match(source,/\.\/lesson\.html\?kpId=/);assert.match(source,/encodeURIComponent\(lesson\.kpId\)/);assert.match(source,/nextLesson\(stage\)/);});
test('lesson page loads browser flow dependencies in safe order',()=>{const html=read('public/lesson.html');const scripts=['./content-catalog.js','./local-learning.js','./lesson-content-reading.js','./lesson-content.js','./local-lesson.js'];let last=-1;for(const src of scripts){const index=html.indexOf(`src="${src}"`);assert.ok(index>last,`${src} missing or loaded out of order`);last=index;}assert.match(html,/new URLSearchParams\(location\.search\)\.get\('kpId'\)/);assert.match(html,/ManjingoLocalLesson\.open\(kpId,app\)/);});
test('local lesson practice submits exact KP result and answer metadata into learning engine',()=>{const source=read('public/local-lesson.js');assert.match(source,/filter\(q=>q\.kpId===kpId\)/);assert.match(source,/ManjingoLocalLearning\.submit\(q\.kpId,correct,\{questionId:q\.id,selectedAnswer:value,correctAnswer:q\.a\}\)/);assert.match(source,/getKnowledge\(state\.kp\.kpId\)/);assert.match(source,/state\.questions\.length/);});
test('targeted weakness practice skips lesson intro and prioritizes misconception questions',()=>{const lesson=read('public/local-lesson.js'),dashboard=read('public/mastery-dashboard.js');assert.match(lesson,/function targetedQuestions\(kpId,limit\)/);assert.match(lesson,/params\.get\('mode'\)==='practice'/);assert.match(lesson,/targeted\?targetedQuestions\(kpId,5\):questions\(kpId,3\)/);assert.match(lesson,/if\(targeted\)\{renderQuestion\(app,state\);return\}/);assert.match(lesson,/weight\.get\(String\(b\.id\)\)/);assert.match(dashboard,/mode=practice/);assert.match(dashboard,/立即補強/);});
test('targeted practice compares mastery before and after and reports round accuracy',()=>{const source=read('public/local-lesson.js');assert.match(source,/startMastery:Number\(p\.mastery\|\|0\)/);assert.match(source,/state\.answeredCount\+=1/);assert.match(source,/if\(correct\)state\.correctCount\+=1/);assert.match(source,/掌握度：/);assert.match(source,/→/);assert.match(source,/本輪答對/);assert.match(source,/state\.correctCount/);});
test('wrong answers prefer per-question feedback and fall back to KP lesson',()=>{const source=read('public/local-lesson.js');assert.match(source,/function teachingFeedback\(state,q,value\)/);assert.match(source,/q&&q\.explanation/);assert.match(source,/q&&q\.misconception/);assert.match(source,/q&&q\.example/);assert.match(source,/lesson\.explanation/);assert.match(source,/lesson\.tip/);assert.match(source,/lesson\.examples/);assert.match(source,/你可能混淆了：/);assert.match(source,/!correct&&normal\(b\.textContent\)===normal\(q\.a\)/);});
test('core particle pack carries question-level teaching metadata',()=>{const context={window:{}};vm.createContext(context);vm.runInContext(read('public/question-pack-03.js'),context);const qs=context.window.ManjingoQuestionPack03.questions;const rich=qs.filter(q=>q.explanation);assert.ok(rich.length>=20);const yi=qs.find(q=>q.q.includes('不以物喜'));assert.ok(yi.explanation);assert.ok(yi.misconception);assert.ok(yi.example);});
test('daily quiz surfaces misconception review and confirms repaired pattern',()=>{const html=read('public/index.html');assert.match(html,/misconceptionReview/);assert.match(html,/🔁 錯題重溫/);assert.match(html,/你已修正這個錯誤模式/);assert.match(html,/這題仍會保留較低的複習權重/);assert.match(html,/resolvedMisconceptions/);assert.match(html,/remainingMisconceptionWeight/);assert.match(html,/resolveQuestionMisconceptions\(q\.kpId,q\.id\)/);assert.match(html,/selectedAnswer:value/);assert.match(html,/correctAnswer:q\.a/);});
test('lesson completion returns learner to learning path',()=>{const source=read('public/local-lesson.js');assert.match(source,/href="\.\/index\.html"/);assert.match(source,/回到學習路徑/);});
