const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const root=path.join(__dirname,'..');
const curriculum=require('../public/curriculum-v1.js');
function source(file){return fs.readFileSync(path.join(root,file),'utf8')}
function loadCatalog(){const context={window:{},Map,Set,Array,Object,Number,String,Math};vm.createContext(context);for(const file of ['public/question-pack-02.js','public/question-pack-03.js','public/question-pack-lesson.js','public/question-pack-capacity-01.js','public/question-pack-transfer-01.js','public/question-pack-transfer-03.js','public/question-pack-transfer-04.js','public/question-pack-transfer-05.js','public/question-pack-transfer-06.js','public/question-pack-transfer-07.js','public/content-catalog.js'])vm.runInContext(source(file),context,{filename:file});return context.window.ManjingoContent;}
const NATIVE=new Map([['kp_virtual_hu','fw.hu'],['kp_virtual_qie','fw.qie'],['kp_virtual_yan','fw.yan'],['kp_lex_tongjia','lex.tongjia'],['kp_lex_intentional','lex.intentional'],['kp_lex_semantic_role','lex.semantic-role'],['kp_syn_attributive_postpose','syn.attributive-postpose'],['kp_syn_fixed_patterns','syn.fixed-patterns'],['kp_read_parallel_inference','read.parallel-inference'],['kp_read_actor_tracking','read.actor-tracking'],['kp_read_unknown_word_tolerance','read.unknown-word-tolerance'],['kp_trans_fluency','trans.fluency'],['kp_transfer_sentence_pair','transfer.sentence-pair'],['kp_transfer_micro_passage','transfer.micro-passage'],['kp_read_argumentation','read.argumentation'],['kp_transfer_short_passage','transfer.short-passage'],['kp_transfer_mixed','transfer.mixed']]);
test('curriculum v1 defines a unique transfer-first skill tree',()=>{assert.equal(curriculum.VERSION,'language-transfer-v1');assert.equal(curriculum.domains.length,6);assert.equal(curriculum.skills.length,52);assert.equal(new Set(curriculum.skills.map(x=>x.id)).size,52);assert.equal(curriculum.coreSkills().length,49);assert.deepEqual(curriculum.advancedSkills().map(x=>x.id),['read.argumentation','transfer.short-passage','transfer.mixed']);});
test('legacy KPs keep migration while native curriculum KPs carry direct skill provenance',()=>{const catalog=loadCatalog(),kpIds=Array.from(catalog.getKnowledgePointIds({teachableOnly:true}),String);assert.equal(kpIds.length,89);const nativeIds=new Set(NATIVE.keys()),legacy=kpIds.filter(id=>!nativeIds.has(id)).sort();assert.deepEqual(Object.keys(curriculum.migration).sort(),legacy);for(const[kpId,skillId]of NATIVE){assert.equal(curriculum.migration[kpId],undefined);const rows=catalog.questions.filter(q=>q.kpId===kpId);assert.equal(rows.length,6);assert.equal(rows.every(q=>Array.isArray(q.skillIds)&&q.skillIds.includes(skillId)),true);}});
test('legacy migration targets only valid curriculum skills',()=>{const ids=new Set(curriculum.skills.map(x=>x.id));for(const[kpId,rule]of Object.entries(curriculum.migration)){assert.ok(['retain','refactor','merge','optional-set-text','advanced-reading'].includes(rule.action),`${kpId}: unknown migration action`);for(const id of rule.targetSkillIds||[])assert.ok(ids.has(id),`${kpId}: missing target skill ${id}`);}});
test('migration removes article recall from the normal core without discarding transferable material',()=>{const counts=Object.values(curriculum.migration).reduce((out,rule)=>{out[rule.action]=(out[rule.action]||0)+1;return out;},{});assert.deepEqual(counts,{refactor:3,'optional-set-text':26,retain:28,'advanced-reading':4,merge:11});assert.equal(curriculum.migration.kp_yueyang_004.action,'optional-set-text');assert.equal(curriculum.migration.kp_theme_001.action,'optional-set-text');});
test('daily policy prioritizes language transfer and caps source repetition',()=>{const p=curriculum.dailyPolicy;assert.deepEqual(p.languageSkillTarget,{min:7,max:8});assert.deepEqual(p.transferTarget,{min:2,max:3});assert.deepEqual(p.setTextRecallTarget,{min:0,max:0});assert.equal(p.maxQuestionsPerSourceText,2);assert.equal(p.maxQuestionsPerSourceSentence,1);assert.equal(p.wrongAnswerFollowup,'same-skill-different-context-first');});
