const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8');
function load(){const context={window:{},Map,Set,Array,Object,Number,String,Math};vm.createContext(context);vm.runInContext(read('public/question-pack-02.js'),context);vm.runInContext(read('public/question-pack-03.js'),context);vm.runInContext(read('public/question-pack-lesson.js'),context);vm.runInContext(read('public/question-pack-capacity-01.js'),context);vm.runInContext(read('public/question-pack-transfer-01.js'),context);vm.runInContext(read('public/question-pack-transfer-03.js'),context);vm.runInContext(read('public/question-pack-transfer-04.js'),context);vm.runInContext(read('public/content-catalog.js'),context);vm.runInContext(read('public/lesson-content-reading.js'),context);vm.runInContext(read('public/lesson-content.js'),context);return context.window}
test('all 67 teachable knowledge points build a usable lesson',()=>{const w=load();const kps=w.ManjingoContent.knowledgePoints.filter(k=>k.teachable!==false);assert.equal(kps.length,67);for(const kp of kps){const lesson=w.ManjingoLessonContent.build(kp);assert.ok(lesson.title,`${kp.kpId} missing lesson title`);assert.ok(lesson.explanation,`${kp.kpId} missing explanation`);assert.ok(lesson.tip,`${kp.kpId} missing tip`);assert.ok(Array.isArray(lesson.examples),`${kp.kpId} examples must be an array`)}});
test('every teachable knowledge point has at least three practice questions',()=>{const w=load();const counts=new Map();for(const q of w.ManjingoContent.questions)counts.set(q.kpId,(counts.get(q.kpId)||0)+1);const under3=w.ManjingoContent.knowledgePoints.filter(k=>k.teachable!==false&&(counts.get(k.kpId)||0)<3).map(k=>[k.kpId,counts.get(k.kpId)||0]);assert.deepEqual(Array.from(under3),[])});
test('new stage 1 function words build language lessons rather than set-text lessons',()=>{const w=load();for(const id of ['kp_virtual_wei','kp_virtual_zhe','kp_virtual_suo','kp_virtual_ye']){const kp=w.ManjingoContent.knowledgePoints.find(x=>x.kpId===id),lesson=w.ManjingoLessonContent.build(kp);assert.ok(kp,`missing ${id}`);assert.match(kp.type,/虛詞/);assert.ok(lesson.explanation.length>0);assert.ok(lesson.tip.length>0)}});
test('new stage 1 reading foundations build transferable language lessons',()=>{const w=load(),ids=['kp_read_sentence_core','kp_read_context_clues','kp_read_logical_relation','kp_syn_negative_patterns'];for(const id of ids){const kp=w.ManjingoContent.knowledgePoints.find(x=>x.kpId===id);assert.ok(kp,`missing ${id}`);const lesson=w.ManjingoLessonContent.build(kp);assert.ok(lesson.title);assert.ok(lesson.explanation.length>0);assert.ok(lesson.tip.length>0);assert.ok(Array.isArray(lesson.examples));assert.equal(kp.textId,'CROSS')}});
test('all dedicated reading lessons point to known knowledge points',()=>{const w=load();const ids=new Set(w.ManjingoContent.knowledgePoints.map(k=>k.kpId));const unknown=Object.keys(w.ManjingoReadingLessons).filter(id=>!ids.has(id));assert.deepEqual(Array.from(unknown),[])});
test('all 48 core pack03 questions have question-level explanations',()=>{const w=load();const pack=w.ManjingoQuestionPack03.questions;assert.equal(pack.length,48);const missing=pack.filter(q=>!q.explanation).map(q=>q.id);assert.deepEqual(Array.from(missing),[])});
test('all 96 reading pack02 questions have teaching explanations',()=>{const w=load();const pack=w.ManjingoQuestionPack02.questions;assert.equal(pack.length,96);const missing=pack.filter(q=>!q.explanation).map(q=>q.id);assert.deepEqual(Array.from(missing),[]);for(const q of pack)assert.match(q.explanation,new RegExp(q.a.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')),`${q.id} explanation should identify its answer`) });
