const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const source = fs.readFileSync(path.join(__dirname, '..', 'public', 'local-learning.js'), 'utf8');
function makeDateClass(nowIso){const RealDate=Date,fixed=new RealDate(nowIso).getTime();return class FakeDate extends RealDate{constructor(...args){super(...(args.length?args:[fixed]))}static now(){return fixed}}}
function createEngine({now='2026-09-10T12:00:00',initial={},questions=[]}={}){const store=new Map(Object.entries(initial));const context={window:{ManjingoContent:{questions}},localStorage:{getItem:key=>store.has(key)?store.get(key):null,setItem:(key,value)=>store.set(key,String(value)),removeItem:key=>store.delete(key)},Date:makeDateClass(now),console,JSON,Math,Number,String,Object,Array,Map,Set};vm.createContext(context);vm.runInContext(source,context);return{engine:context.window.ManjingoLocalLearning,store}}
function progressState(store){return JSON.parse(store.get('manjingo_progress_cache')||'{}')}
test('correct local answer awards exactly 8 XP; wrong answer awards 0',()=>{const{engine}=createEngine();const correct=engine.submit('kp_test',true);assert.equal(correct.xpEarned,8);assert.equal(correct.totalXp,8);assert.equal(correct.todayXp,8);const wrong=engine.submit('kp_test',false);assert.equal(wrong.xpEarned,0);assert.equal(wrong.totalXp,8);assert.equal(wrong.todayXp,8)});
test('wrong answers record selected misconception and increment repeats',()=>{const{engine,store}=createEngine();const detail={questionId:'p3q009',selectedAnswer:'用',correctAnswer:'因為'};engine.submit('kp_p3_yi',false,detail);engine.submit('kp_p3_yi',false,detail);const record=engine.getKnowledge('kp_p3_yi'),key='p3q009::用';assert.equal(record.misconceptions[key].count,2);assert.equal(record.misconceptions[key].lastAt,'2026-09-10T12:00:00.000Z');assert.equal(progressState(store).knowledge.kp_p3_yi.misconceptions[key].count,2)});
test('misconceptions from different questions aggregate under one concept',()=>{const{engine}=createEngine();engine.submit('kp_p3_yi',false,{questionId:'p3q009',selectedAnswer:'用',correctAnswer:'因為',conceptKey:'yi_reason_vs_tool',conceptLabel:'「以」：原因義 vs 工具義'});engine.submit('kp_p3_yi',false,{questionId:'p3q012',selectedAnswer:'以刀劈狼首',correctAnswer:'不以物喜',conceptKey:'yi_reason_vs_tool',conceptLabel:'「以」：原因義 vs 工具義'});engine.submit('kp_p3_yi',false,{questionId:'p3q009',selectedAnswer:'用',correctAnswer:'因為',conceptKey:'yi_reason_vs_tool',conceptLabel:'「以」：原因義 vs 工具義'});const concepts=engine.getMisconceptionConcepts('kp_p3_yi');assert.equal(concepts[0].conceptKey,'yi_reason_vs_tool');assert.equal(concepts[0].count,3);assert.deepEqual(Array.from(concepts[0].questionIds).sort(),['p3q009','p3q012']);assert.equal(concepts[0].answers.length,2)});
test('concept mastery is independent from KP mastery and shared across KP aliases',()=>{const{engine}=createEngine();const concept={conceptKey:'yi_reason_vs_tool',conceptLabel:'「以」：原因義 vs 工具義'};engine.submit('kp_p3_yi',false,{questionId:'p3q009',selectedAnswer:'用',correctAnswer:'因為',...concept});engine.submit('kp_virtual_yi',true,{questionId:'virtual_yi_reason',selectedAnswer:'因為',correctAnswer:'因為',...concept});const c=engine.getConceptMastery('yi_reason_vs_tool');assert.equal(c.attempts,2);assert.equal(c.correctCount,1);assert.equal(c.mastery,22);assert.equal(c.lastCorrect,true);assert.deepEqual(Array.from(c.kpIds).sort(),['kp_p3_yi','kp_virtual_yi']);assert.equal(engine.getKnowledge('kp_p3_yi').mastery,0);assert.equal(engine.getKnowledge('kp_virtual_yi').mastery,22)});
test('legacy concept-tagged misconceptions initialize concept mastery as weak',()=>{const initial={totalXp:0,todayXp:0,streak:0,todayDate:'2026-09-10',knowledge:{kp_p3_yi:{mastery:50,misconceptions:{'q1::用':{questionId:'q1',selectedAnswer:'用',correctAnswer:'因為',count:3,lastAt:'2026-09-09T12:00:00.000Z',conceptKey:'yi_reason_vs_tool',conceptLabel:'「以」：原因義 vs 工具義'}}}},practiceHistory:[]};const{engine,store}=createEngine({initial:{manjingo_progress_cache:JSON.stringify(initial)}});engine.getProgress();const c=engine.getConceptMastery('yi_reason_vs_tool');assert.equal(c.mastery,0);assert.equal(c.attempts,3);assert.equal(c.lastCorrect,false);assert.deepEqual(Array.from(c.questionIds),['q1']);assert.ok(progressState(store).conceptMastery.yi_reason_vs_tool)});
test('correct misconception review decays weight until the pattern retires',()=>{const{engine}=createEngine(),detail={questionId:'p3q009',selectedAnswer:'用',correctAnswer:'因為'};engine.submit('kp_p3_yi',false,detail);engine.submit('kp_p3_yi',false,detail);const first=engine.submit('kp_p3_yi',true,{questionId:'p3q009',selectedAnswer:'因為',correctAnswer:'因為'});assert.equal(first.remainingMisconceptionWeight,1);const second=engine.submit('kp_p3_yi',true,{questionId:'p3q009',selectedAnswer:'因為',correctAnswer:'因為'});assert.equal(second.remainingMisconceptionWeight,0);assert.equal(engine.getKnowledge('kp_p3_yi').misconceptions['p3q009::用'],undefined)});
test('synced correct answer can repair misconception without local XP duplication',()=>{const questions=[{id:'p3q009',kpId:'kp_p3_yi',misconceptionKey:'yi_reason_vs_tool',misconceptionLabel:'「以」：原因義 vs 工具義'}];const{engine}=createEngine({questions});engine.submit('kp_p3_yi',false,{questionId:'p3q009',selectedAnswer:'用',correctAnswer:'因為'});const before=engine.getProgress(),repair=engine.resolveQuestionMisconceptions('kp_p3_yi','p3q009'),after=engine.getProgress();assert.equal(repair.resolvedMisconceptions,1);assert.equal(repair.conceptMastery.mastery,22);assert.equal(after.totalXp,before.totalXp);assert.equal(after.todayXp,before.todayXp)});
test('targeted practice history persists outcome and computes accuracy',()=>{const{engine,store}=createEngine();const entry=engine.recordPracticeSession({kpId:'kp_virtual_yi',beforeMastery:32,afterMastery:51,correctCount:4,questionCount:5});assert.equal(entry.delta,19);assert.equal(entry.accuracy,80);assert.equal(entry.completedAt,'2026-09-10T12:00:00.000Z');const history=engine.getPracticeHistory({kpId:'kp_virtual_yi'});assert.equal(history.length,1);assert.equal(history[0].afterMastery,51);assert.equal(progressState(store).practiceHistory.length,1)});
test('practice history supports recent-day filtering',()=>{const old={totalXp:0,todayXp:0,streak:0,todayDate:'2026-09-10',knowledge:{},practiceHistory:[{kpId:'old',delta:10,completedAt:'2026-08-20T12:00:00.000Z'},{kpId:'recent',delta:5,completedAt:'2026-09-08T12:00:00.000Z'}]};const{engine}=createEngine({initial:{manjingo_progress_cache:JSON.stringify(old)}});assert.deepEqual(Array.from(engine.getPracticeHistory({days:7}),x=>x.kpId),['recent'])});
test('low-yield repeated targeted practice triggers remediation',()=>{const initial={totalXp:0,todayXp:0,streak:0,todayDate:'2026-09-10',knowledge:{},practiceHistory:[{kpId:'kp_virtual_er',delta:3,accuracy:60,completedAt:'2026-09-09T12:00:00.000Z'},{kpId:'kp_virtual_er',delta:2,accuracy:50,completedAt:'2026-09-08T12:00:00.000Z'}]};const{engine}=createEngine({initial:{manjingo_progress_cache:JSON.stringify(initial)}}),status=engine.getRemediationStatus('kp_virtual_er');assert.equal(status.sessions,2);assert.equal(status.totalDelta,5);assert.equal(status.averageAccuracy,55);assert.equal(status.needsRemediation,true)});
test('strong recent improvement avoids remediation',()=>{const initial={totalXp:0,todayXp:0,streak:0,todayDate:'2026-09-10',knowledge:{},practiceHistory:[{kpId:'kp_virtual_yi',delta:6,accuracy:80,completedAt:'2026-09-09T12:00:00.000Z'},{kpId:'kp_virtual_yi',delta:5,accuracy:80,completedAt:'2026-09-08T12:00:00.000Z'}]};const{engine}=createEngine({initial:{manjingo_progress_cache:JSON.stringify(initial)}});assert.equal(engine.getRemediationStatus('kp_virtual_yi').needsRemediation,false)});
test('daily plan orders misconception question ids by repeated error count',()=>{const initial={totalXp:0,todayXp:0,streak:0,todayDate:'2026-09-10',knowledge:{kp_p3_yi:{mastery:20,repetition:0,easeFactor:2.3,interval:1,nextReviewAt:'2026-09-10T10:00:00.000Z',attempts:5,correctCount:1,lastCorrect:false,lastAnsweredAt:'2026-09-10T10:00:00.000Z',misconceptions:{'p3q009::用':{questionId:'p3q009',count:3},'p3q010::因為':{questionId:'p3q010',count:1},'p3q009::按照':{questionId:'p3q009',count:2}}}}};const{engine}=createEngine({initial:{manjingo_progress_cache:JSON.stringify(initial)}});assert.deepEqual(Array.from(engine.buildDailyPlan(['kp_p3_yi'],1).items[0].misconceptionQuestionIds),['p3q009','p3q010'])});
test('daily plan schedules weak concept even when overall KP mastery is strong',()=>{const initial={totalXp:0,todayXp:0,streak:0,todayDate:'2026-09-10',knowledge:{kp_virtual_yi:{mastery:80,repetition:3,easeFactor:2.5,interval:6,nextReviewAt:'2026-09-20T12:00:00.000Z',attempts:8,correctCount:6,lastCorrect:true,lastAnsweredAt:'2026-09-09T12:00:00.000Z',misconceptions:{}}},conceptMastery:{yi_reason_vs_tool:{conceptKey:'yi_reason_vs_tool',conceptLabel:'「以」：原因義 vs 工具義',mastery:30,attempts:4,correctCount:1,lastCorrect:false,lastAnsweredAt:'2026-09-09T12:00:00.000Z',kpIds:['kp_virtual_yi'],questionIds:['concept_q1']}},practiceHistory:[]};const questions=[{id:'concept_q1',kpId:'kp_virtual_yi',misconceptionKey:'yi_reason_vs_tool'}];const{engine}=createEngine({initial:{manjingo_progress_cache:JSON.stringify(initial)},questions}),plan=engine.buildDailyPlan(['kp_virtual_yi'],1);assert.equal(plan.items[0].category,'weak');assert.equal(plan.items[0].conceptReview,true);assert.equal(plan.items[0].conceptKey,'yi_reason_vs_tool');assert.equal(plan.items[0].conceptMastery,30);assert.deepEqual(Array.from(plan.items[0].conceptQuestionIds),['concept_q1']);assert.equal(plan.conceptReview[0].conceptKey,'yi_reason_vs_tool')});
test('daily goal increments streak once, not on every answer after goal',()=>{const{engine}=createEngine();engine.submit('a',true);engine.submit('b',true);assert.equal(engine.submit('c',true).streak,1);assert.equal(engine.submit('d',true).streak,1)});
test('legacy knowledge state migrates without losing mastery',()=>{const legacy={kp_old:{mastery:72,repetition:3,easeFactor:2.4,interval:12,nextReviewAt:'2026-09-15T12:00:00.000Z',attempts:7,correctCount:5,lastCorrect:true,lastAnsweredAt:'2026-09-09T12:00:00.000Z'}};const{engine,store}=createEngine({initial:{manjingo_learning_state_v1:JSON.stringify(legacy)}});assert.equal(engine.getKnowledge('kp_old').mastery,72);assert.equal(progressState(store).knowledge.kp_old.mastery,72)});
test('remote gamification sync becomes the rendered local progress source',()=>{const{engine}=createEngine();engine.syncGamification({totalXp:120,todayXp:16,streak:5});const p=engine.getProgress();assert.equal(p.totalXp,120);assert.equal(p.todayXp,16);assert.equal(p.streak,5)});
