const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8');
function load(customKnowledge,history=[],options={}){const context={window:{},Map,Set,Array,Object,Number,String,Math,RegExp};vm.createContext(context);vm.runInContext(read('public/question-pack-02.js'),context);vm.runInContext(read('public/question-pack-03.js'),context);vm.runInContext(read('public/question-pack-lesson.js'),context);vm.runInContext(read('public/content-catalog.js'),context);context.window.ManjingoLocalLearning={getKnowledge(kpId){if(customKnowledge&&Object.prototype.hasOwnProperty.call(customKnowledge,kpId))return customKnowledge[kpId];if(options.fallback===false)return{mastery:0,attempts:0,lastCorrect:null,lastAnsweredAt:null,misconceptions:{}};return{mastery:kpId==='kp_virtual_zhi'?100:50,attempts:1,lastCorrect:true,misconceptions:{}}},getPracticeHistory(){return history}};vm.runInContext(read('public/practice-effectiveness.js'),context);context.window.ManjingoPracticeEffectiveness=context.ManjingoPracticeEffectiveness;vm.runInContext(read('public/mastery-dashboard.js'),context);return context.window.ManjingoMasteryDashboard;}
test('mastery dashboard covers all 59 teachable knowledge points in six learning groups',()=>{const d=load().build();assert.equal(d.total,59);assert.equal(d.groups.length,6);assert.deepEqual(Array.from(d.groups,g=>g.title),['實詞','虛詞','句式','翻譯','篇章','論證'])});
test('mastery dashboard derives overall, mastered and weak counts from local learning state',()=>{const d=load().build();assert.equal(d.overall,51);assert.equal(d.mastered,1);assert.equal(d.weak,58);assert.equal(d.unattempted,0)});
test('untouched knowledge points stay pending instead of being counted as weak',()=>{const dashboard=load({},[],{fallback:false}),d=dashboard.build();assert.equal(d.total,59);assert.equal(d.attempted,0);assert.equal(d.unattempted,59);assert.equal(d.weak,0);assert.equal(d.mastered,0);assert.equal(d.groups.reduce((n,g)=>n+g.unattempted,0),59);assert.equal(dashboard.weakest(d.groups.find(g=>g.id==='particles'),3).length,0)});
test('attempted zero-mastery knowledge point is correctly classified as weak',()=>{const dashboard=load({kp_virtual_er:{mastery:0,attempts:1,lastCorrect:false,lastAnsweredAt:'2026-09-10T12:00:00.000Z',misconceptions:{}}},[],{fallback:false}),d=dashboard.build(),particles=d.groups.find(g=>g.id==='particles');assert.equal(d.attempted,1);assert.equal(d.unattempted,58);assert.equal(d.weak,1);assert.equal(particles.weak,1);assert.deepEqual(Array.from(dashboard.weakest(particles,3),x=>x.kpId),['kp_virtual_er'])});
test('dashboard weakest drilldown prioritizes recent mistakes then lower mastery',()=>{const dashboard=load({kp_virtual_zhi:{mastery:70,lastCorrect:true,misconceptions:{}},kp_virtual_er:{mastery:60,lastCorrect:false,misconceptions:{}},kp_virtual_yi:{mastery:20,lastCorrect:true,misconceptions:{'q::x':{count:4}}},kp_virtual_yu:{mastery:40,lastCorrect:false,misconceptions:{}}});const particles=dashboard.build().groups.find(g=>g.id==='particles');assert.deepEqual(Array.from(dashboard.weakest(particles,3),x=>x.kpId),['kp_virtual_yu','kp_virtual_er','kp_virtual_yi'])});
test('dashboard trend insights rank recent improvement and flag repeated low-gain practice',()=>{const history=[{kpId:'kp_virtual_yi',delta:12,accuracy:80},{kpId:'kp_virtual_yi',delta:8,accuracy:100},{kpId:'kp_virtual_er',delta:2,accuracy:60},{kpId:'kp_virtual_er',delta:1,accuracy:40},{kpId:'kp_virtual_yu',delta:7,accuracy:80}];const trends=load(null,history).trendData();assert.equal(trends.improved[0].kpId,'kp_virtual_yi');assert.equal(trends.improved[0].delta,20);assert.equal(trends.stuck[0].kpId,'kp_virtual_er');assert.equal(trends.stuck[0].sessions,2);assert.equal(trends.stuck[0].accuracy,50)});
test('dashboard does not flag high-mastery strong-accuracy practice as stuck just because gains are small',()=>{const knowledge={kp_virtual_zhi:{mastery:95,attempts:10,lastCorrect:true,misconceptions:{}}},history=[{kpId:'kp_virtual_zhi',beforeMastery:92,afterMastery:94,delta:2,accuracy:100,strategy:'targeted'},{kpId:'kp_virtual_zhi',beforeMastery:94,afterMastery:95,delta:1,accuracy:100,strategy:'targeted'}],trends=load(knowledge,history).trendData();assert.equal(trends.stuck.some(x=>x.kpId==='kp_virtual_zhi'),false)});
test('ability trend only counts practice history from that learning group',()=>{const dashboard=load(null,[{kpId:'kp_virtual_yi',delta:8,accuracy:100},{kpId:'kp_virtual_er',delta:4,accuracy:50},{kpId:'kp_translation_001',delta:20,accuracy:100}]),data=dashboard.build(),particles=data.groups.find(g=>g.id==='particles'),trend=dashboard.groupTrendData(particles);assert.equal(trend.sessions,2);assert.equal(trend.totalDelta,12);assert.equal(trend.accuracy,75);assert.equal(trend.best.kpId,'kp_virtual_yi')});
test('results UI defaults to overall mastery and six compact ability cards with details on demand',()=>{const source=read('public/mastery-dashboard.js');assert.match(source,/六大能力掌握度總覽/);assert.match(source,/dashboard-hero/);assert.match(source,/dashboard-groups/);assert.match(source,/grid-template-columns:repeat\(2,minmax\(0,1fr\)\)/);assert.match(source,/查看知識點與近 7 天趨勢/);assert.match(source,/dashboard-detail" hidden/);assert.match(source,/最需要補強/);assert.match(source,/groupTrendHtml\(g\)/);assert.match(source,/查看全部近 7 天趨勢/)});
test('dashboard drilldown links weak knowledge points directly to targeted practice',()=>{const source=read('public/mastery-dashboard.js');assert.match(source,/mode=practice/);assert.match(source,/立即補強/);assert.match(source,/最近提升最多/);assert.match(source,/多次補強仍需留意/);assert.match(source,/待學習/);assert.match(source,/目前沒有已嘗試但需要補強的知識點/)});
test('content catalog loads practice policy before mastery dashboard on browser pages',()=>{const source=read('public/content-catalog.js');assert.match(source,/practice-effectiveness\.js[\s\S]*mastery-dashboard\.js/);const dashboard=read('public/mastery-dashboard.js');assert.match(dashboard,/ManjingoPracticeEffectiveness/);assert.match(dashboard,/學習成果/);assert.match(dashboard,/masteryDashboard/);assert.match(dashboard,/DOMContentLoaded/)});