const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8');
function load(customKnowledge,history=[],options={}){const context={window:{},Map,Set,Array,Object,Number,String,Math,RegExp,Date};vm.createContext(context);for(const file of ['public/question-pack-02.js','public/question-pack-03.js','public/question-pack-lesson.js','public/question-pack-transfer-03.js','public/question-pack-transfer-04.js','public/question-pack-transfer-05.js','public/question-pack-transfer-06.js','public/content-catalog.js'])vm.runInContext(read(file),context);context.window.ManjingoLocalLearning={getKnowledge(kpId){if(customKnowledge&&Object.prototype.hasOwnProperty.call(customKnowledge,kpId))return customKnowledge[kpId];if(options.fallback===false)return{mastery:0,attempts:0,lastCorrect:null,lastAnsweredAt:null,misconceptions:{}};return{mastery:kpId==='kp_virtual_zhi'?100:50,attempts:1,lastCorrect:true,misconceptions:{}}},getPracticeHistory(){return history}};vm.runInContext(read('public/practice-effectiveness.js'),context);context.window.ManjingoPracticeEffectiveness=context.ManjingoPracticeEffectiveness;vm.runInContext(read('public/mastery-dashboard.js'),context);return context.window.ManjingoMasteryDashboard;}
test('mastery dashboard covers all 78 teachable knowledge points in six learning groups',()=>{const d=load().build();assert.equal(d.total,78);assert.equal(d.groups.length,6);assert.deepEqual(Array.from(d.groups,g=>g.title),['實詞','虛詞','句式','翻譯','篇章','論證'])});
test('mastery dashboard derives overall mastered and weak counts from local learning state',()=>{const d=load().build();assert.equal(d.overall,51);assert.equal(d.mastered,1);assert.equal(d.weak,77);assert.equal(d.unattempted,0)});
test('untouched knowledge points stay pending instead of being counted as weak',()=>{const dashboard=load({},[],{fallback:false}),d=dashboard.build();assert.equal(d.total,78);assert.equal(d.attempted,0);assert.equal(d.unattempted,78);assert.equal(d.weak,0);assert.equal(d.mastered,0)});
test('attempted zero-mastery knowledge point is correctly classified as weak',()=>{const dashboard=load({kp_virtual_er:{mastery:0,attempts:1,lastCorrect:false,lastAnsweredAt:'2026-09-10T12:00:00.000Z',misconceptions:{}}},[],{fallback:false}),d=dashboard.build(),particles=d.groups.find(g=>g.id==='particles');assert.equal(d.attempted,1);assert.equal(d.unattempted,77);assert.equal(d.weak,1);assert.deepEqual(Array.from(dashboard.weakest(particles,3),x=>x.kpId),['kp_virtual_er'])});
test('stage 2 function words appear in the particle mastery group',()=>{const ids=new Set(load({},[],{fallback:false}).build().groups.find(g=>g.id==='particles').items.map(x=>x.kpId));for(const id of ['kp_virtual_hu','kp_virtual_qie','kp_virtual_yan'])assert.ok(ids.has(id),`${id} missing from particle group`)});
test('stage 2 lexical skills appear in the words mastery group',()=>{const ids=new Set(load({},[],{fallback:false}).build().groups.find(g=>g.id==='words').items.map(x=>x.kpId));for(const id of ['kp_lex_tongjia','kp_lex_intentional','kp_lex_semantic_role'])assert.ok(ids.has(id),`${id} missing from words group`)});
test('existing foundation and transfer KPs remain grouped',()=>{const data=load({},[],{fallback:false}).build();assert.ok(data.groups.find(g=>g.id==='particles').items.some(x=>x.kpId==='kp_virtual_wei'));assert.ok(data.groups.find(g=>g.id==='reading').items.some(x=>x.kpId==='kp_transfer_single_sentence'));});
test('dashboard weakest drilldown prioritizes recent mistakes then lower mastery',()=>{const dashboard=load({kp_virtual_zhi:{mastery:70,lastCorrect:true,misconceptions:{}},kp_virtual_er:{mastery:60,lastCorrect:false,misconceptions:{}},kp_virtual_yi:{mastery:20,lastCorrect:true,misconceptions:{'q::x':{count:4}}},kp_virtual_yu:{mastery:40,lastCorrect:false,misconceptions:{}}});const particles=dashboard.build().groups.find(g=>g.id==='particles');assert.deepEqual(Array.from(dashboard.weakest(particles,3),x=>x.kpId),['kp_virtual_yu','kp_virtual_er','kp_virtual_yi'])});
test('dashboard trend insights rank recent improvement and flag repeated low-gain practice',()=>{const history=[{kpId:'kp_virtual_yi',delta:12,accuracy:80},{kpId:'kp_virtual_yi',delta:8,accuracy:100},{kpId:'kp_virtual_er',delta:2,accuracy:60},{kpId:'kp_virtual_er',delta:1,accuracy:40}];const trends=load(null,history).trendData();assert.equal(trends.improved[0].kpId,'kp_virtual_yi');assert.equal(trends.stuck[0].kpId,'kp_virtual_er')});
test('results UI retains learning guidance and drilldown controls',()=>{const source=read('public/mastery-dashboard.js');assert.match(source,/六大能力掌握度總覽/);assert.match(source,/最需要補強/);assert.match(source,/查看全部近 7 天趨勢/);assert.match(source,/mode=practice/)});
test('content catalog loads practice policy before mastery dashboard on browser pages',()=>{const source=read('public/content-catalog.js');assert.match(source,/practice-effectiveness\.js[\s\S]*mastery-dashboard\.js/)});
