const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const root=path.join(__dirname,'..');
const curriculum=require(path.join(root,'public','curriculum-v1.js'));
const metadata=require(path.join(root,'public','question-metadata-v1.js'));
function source(file){return fs.readFileSync(path.join(root,file),'utf8');}
function loadCatalog(){const context={window:{},Map,Set,Array,Object,Number,String,Math};vm.createContext(context);for(const file of ['public/question-pack-02.js','public/question-pack-03.js','public/question-pack-lesson.js','public/question-pack-capacity-01.js','public/question-pack-transfer-01.js','public/question-pack-transfer-03.js','public/question-pack-transfer-04.js','public/question-pack-transfer-05.js','public/question-pack-transfer-06.js','public/content-catalog.js'])vm.runInContext(source(file),context,{filename:file});return context.window.ManjingoContent;}
function byId(questions,id){const found=questions.find(q=>q.id===id);assert.ok(found,`missing question ${id}`);return found;}
test('all 346 reviewed questions receive a curriculum mode',()=>{const questions=metadata.annotateAll(loadCatalog().questions),valid=new Set(curriculum.skills.map(x=>x.id));assert.equal(questions.length,346);assert.equal(questions.some(q=>q.curriculumMode==='unmapped'),false);for(const q of questions){assert.ok(['core','set-text','advanced'].includes(q.curriculumMode));assert.ok(Array.isArray(q.skillIds));if(q.curriculumMode==='core')assert.ok(q.skillIds.length>0,`${q.id}: core question has no skill`);for(const id of q.skillIds)assert.ok(valid.has(id),`${q.id}: unknown skill ${id}`);}});
test('pure set-text recall leaves normal core while transferable questions are salvaged',()=>{const q=metadata.annotateAll(loadCatalog().questions);assert.equal(byId(q,'q008').curriculumMode,'set-text');assert.equal(byId(q,'lpq052').curriculumMode,'set-text');assert.equal(byId(q,'p2q042').curriculumMode,'set-text');assert.deepEqual(Array.from(byId(q,'p2q041').skillIds),['lex.ancient-modern']);assert.deepEqual(Array.from(byId(q,'p2q057').skillIds),['lex.context-inference']);assert.deepEqual(Array.from(byId(q,'p2q071').skillIds),['syn.object-fronting']);assert.deepEqual(Array.from(byId(q,'p2q034').skillIds),['lex.causative']);assert.deepEqual(Array.from(byId(q,'cap1q025').skillIds),['fw.nai']);});
test('new transfer questions keep explicit skills provenance and transfer level',()=>{const q=metadata.annotateAll(loadCatalog().questions),checks=[['tr1q001','fw.zhi','lunyu'],['tr2q005','trans.reorder','lianpo'],['tr3q001','fw.wei','liuguolun'],['tr4q001','read.sentence-core','shishuo'],['tr4q024','syn.negative-patterns','lunyu'],['tr5q001','syn.interrogative-patterns','lunyu'],['tr5q007','trans.function-word','lunyu'],['tr5q013','trans.supplement','hongmenyan'],['tr5q019','trans.ancient-modern','chushibiao'],['tr6q001','transfer.single-sentence','quanxue'],['tr6q006','transfer.single-sentence','lunyu']];for(const[id,skill,sourceText]of checks){const row=byId(q,id);assert.ok(row.skillIds.includes(skill),`${id} must include ${skill}`);assert.equal(row.sourceTextId,sourceText);assert.equal(row.curriculumMode,'core');assert.equal(row.normalCore,true);assert.equal(row.sourceKind,'classical-canon');assert.ok(row.transferLevel>=2);}});
test('cross-tagged transfer evidence preserves every credited skill',()=>{const q=metadata.annotateAll(loadCatalog().questions);assert.deepEqual(Array.from(byId(q,'tr5q010').skillIds),['trans.function-word','syn.judgment']);assert.deepEqual(Array.from(byId(q,'tr5q017').skillIds),['trans.supplement','syn.ellipsis-subject']);assert.deepEqual(Array.from(byId(q,'tr5q019').skillIds),['trans.ancient-modern','lex.ancient-modern']);assert.deepEqual(Array.from(byId(q,'tr6q001').skillIds),['transfer.single-sentence','lex.context-inference']);assert.deepEqual(Array.from(byId(q,'tr6q003').skillIds),['transfer.single-sentence','lex.polysemy']);});
test('advanced argumentation remains available but does not compete in the normal language core',()=>{const q=metadata.annotateAll(loadCatalog().questions);for(const id of ['lpq055','lpq058','lpq061','p3q045']){const row=byId(q,id);assert.equal(row.curriculumMode,'advanced');assert.equal(row.normalCore,false);assert.deepEqual(Array.from(row.skillIds),['read.argumentation']);}});
test('sentence-level identity catches repeated wording across different question ids and packs',()=>{const q=metadata.annotateAll(loadCatalog().questions);for(const ids of [['q006','q010','cap1q013','cap1q014','cap1q015','p3q029','p3q041'],['p2q071','p2q072','lpq045','p3q030'],['tr2q001','tr3q004'],['tr1q002','tr4q013'],['tr1q001','tr5q007'],['tr3q001','tr5q009']])assert.equal(new Set(ids.map(id=>byId(q,id).sourceSentenceId)).size,1,`shared sentence mismatch: ${ids.join(',')}`);});
test('legacy CROSS is separated from the real source text when provenance is known',()=>{const q=metadata.annotateAll(loadCatalog().questions),y=byId(q,'p3q009'),z=byId(q,'lpq007'),g=byId(q,'p3q008');assert.equal(y.legacyTextId,'CROSS');assert.equal(y.sourceTextId,'yueyanglou');assert.equal(y.sourceKind,'set-text');assert.equal(z.sourceTextId,'zuiwengtingji');assert.equal(z.sourceKind,'classical-canon');assert.equal(g.sourceTextId,'CROSS');assert.equal(g.sourceKind,'mixed');});
test('normal core filter excludes set-text recall without deleting the original catalog',()=>{const c=loadCatalog(),core=metadata.normalCoreQuestions(c.questions),ids=new Set(core.map(q=>q.id));assert.equal(c.questions.length,346);assert.equal(core.length,255);for(const id of ['q008','lpq053','p2q042'])assert.equal(ids.has(id),false);for(const id of ['p2q041','p2q071','p3q029','tr1q001','tr2q001','tr3q001','tr4q001','tr4q024','tr5q001','tr5q024','tr6q001','tr6q006'])assert.equal(ids.has(id),true);});
test('audit quantifies legacy content and keeps transfer sources out of CROSS',()=>{const audit=metadata.audit(loadCatalog().questions);assert.equal(audit.total,346);assert.equal(Object.values(audit.byMode).reduce((a,b)=>a+b,0),346);assert.equal(audit.byMode.core,255);assert.equal(audit.byMode['set-text'],78);assert.equal(audit.byMode.advanced,13);assert.equal(audit.bySourceText.yueyanglou,38);assert.equal(audit.bySourceText.CROSS,45);assert.equal(audit.bySourceText.lunyu,25);assert.equal(audit.bySourceText.quanxue,19);assert.equal(audit.bySourceText['mengzi-lianghuiwang-xia'],6);assert.equal(audit.bySourceText.xiaoyaoyou,10);assert.equal(audit.bySourceText.lianpo,19);});
