const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const root=path.join(__dirname,'..');
const source=file=>fs.readFileSync(path.join(root,file),'utf8');
const difficulty=require('../public/question-difficulty.js');
const CORE_KPS=['kp_virtual_zhi','kp_virtual_er','kp_virtual_yi','kp_virtual_yu','kp_virtual_qi','kp_virtual_ze','sx_001','sx_003','sx_004','sx_005','sx_006','sx_008'];
const LATER_STAGE_KPS=['kp_p3_translation','kp_theme_001','kp_yueyang_emotion','kp_chushi_loyalty','kp_chushi_reward','kp_chushi_experience','kp_fish_shame','kp_caogui_trust','kp_caogui_strategy','kp_zouji_selfknowledge','kp_taohua_society','kp_maqianli_ignorance','kp_argument_001','kp_argument_002','kp_argument_003','kp_p3_argument','kp_yueyang_scene','kp_fish_righteousness','kp_shengyou_adversity','kp_shengyou_country','kp_zouji_remonstrance','kp_loushi_character','kp_ai_lotus_symbol','kp_ai_lotus_contrast','kp_maqianli_talent','kp_xiaoshi_pool','kp_xiaoshi_mood'];
const COMPLETION_KPS=['kp_yueyang_001','kp_yueyang_004','gj_004','gj_005','cy_004','cy_006','kp_translation_001','kp_yueyang_context','kp_taohua_discovery','kp_loushi_allusion','kp_p3_zhi','kp_p3_er','kp_p3_yi','kp_p3_yu','kp_p3_qi','kp_p3_judgment','kp_p3_passive','kp_p3_fronting','kp_p3_adverbial','kp_p3_ellipsis'];
const STAGE2_KPS=['kp_virtual_hu','kp_virtual_qie','kp_virtual_yan','kp_lex_tongjia','kp_lex_intentional','kp_lex_semantic_role','kp_syn_attributive_postpose','kp_syn_fixed_patterns','kp_read_parallel_inference','kp_read_actor_tracking','kp_read_unknown_word_tolerance','kp_trans_fluency','kp_transfer_sentence_pair','kp_transfer_micro_passage'];
function loadAdaptivePack(file,key){const context={window:{},Map,Set,Array,Object,Number,String,Math};vm.createContext(context);vm.runInContext(source(file),context);return context.window[key];}
function loadReviewedRuntime(){const context={window:{},Map,Set,Array,Object,Number,String,Math};vm.createContext(context);for(const file of ['public/question-pack-02.js','public/question-pack-03.js','public/question-pack-lesson.js','public/question-pack-capacity-01.js','public/question-pack-transfer-01.js','public/question-pack-transfer-03.js','public/question-pack-transfer-04.js','public/question-pack-transfer-05.js','public/question-pack-transfer-06.js','public/content-catalog.js','public/question-pack-adaptive-01.js','public/question-pack-adaptive-02.js','public/question-pack-adaptive-03.js','public/question-difficulty.js'])vm.runInContext(source(file),context,{filename:file});return context.window;}
test('mastery maps to foundation application and transfer tiers',()=>{assert.equal(difficulty.tierForMastery(0),'foundation');assert.equal(difficulty.tierForMastery(39),'foundation');assert.equal(difficulty.tierForMastery(40),'application');assert.equal(difficulty.tierForMastery(74),'application');assert.equal(difficulty.tierForMastery(75),'transfer');assert.equal(difficulty.tierForMastery(100),'transfer');});
test('recent mistakes temporarily step difficulty down while intervention modes override mastery',()=>{assert.equal(difficulty.tierForMastery(82,{lastCorrect:false}),'application');assert.equal(difficulty.tierForMastery(62,{lastCorrect:false}),'foundation');assert.equal(difficulty.tierForMastery(95,{mode:'remedial'}),'foundation');assert.equal(difficulty.tierForMastery(10,{mode:'reteach'}),'transfer');});
test('adaptive pack gives every core particle and sentence KP all three tiers',()=>{const pack=loadAdaptivePack('public/question-pack-adaptive-01.js','ManjingoQuestionPackAdaptive01');assert.equal(pack.questions.length,36);for(const kpId of CORE_KPS)assert.deepEqual([...new Set(pack.questions.filter(q=>q.kpId===kpId).map(q=>q.difficultyTier))].sort(),['application','foundation','transfer']);});
test('later-stage pack adds only purposeful transfer questions and explicit existing-question tiers',()=>{const pack=loadAdaptivePack('public/question-pack-adaptive-02.js','ManjingoQuestionPackAdaptive02');assert.equal(pack.catalogVersion,'reviewed-v3');assert.equal(pack.questions.length,LATER_STAGE_KPS.length);assert.deepEqual(new Set(pack.questions.map(q=>q.kpId)),new Set(LATER_STAGE_KPS));for(const q of pack.questions){assert.equal(q.difficultyTier,'transfer');assert.ok(q.q&&q.explanation&&q.a);assert.ok(Array.isArray(q.o)&&q.o.includes(q.a));}});
test('completion pack reuses curated material and adds only seven missing transfer questions',()=>{const pack=loadAdaptivePack('public/question-pack-adaptive-03.js','ManjingoQuestionPackAdaptive03');assert.equal(pack.catalogVersion,'reviewed-v4');assert.equal(COMPLETION_KPS.length,20);assert.equal(pack.questions.length,7);for(let group=0;group<4;group++){const start=group*6+1,ids=Array.from({length:6},(_,i)=>`tr3q${String(start+i).padStart(3,'0')}`);assert.deepEqual(ids.map(id=>pack.tierRevisions[id]),['foundation','foundation','application','application','transfer','transfer']);}});
test('tier ranking prefers the target level but lets unseen adjacent material rotate ahead of a repeated exact-tier item',()=>{const list=[{id:'f',kpId:'k',difficultyTier:'foundation'},{id:'a',kpId:'k',difficultyTier:'application'},{id:'t',kpId:'k',difficultyTier:'transfer'}];assert.equal(difficulty.rank(list,{mastery:80,rotation:{recentIds:()=>[]}})[0].id,'t');assert.equal(difficulty.rank(list,{mastery:80,rotation:{recentIds:()=>['t']}})[0].id,'a');});
test('misconception-targeted question stays ahead of difficulty preference',()=>{const list=[{id:'foundation',kpId:'k',difficultyTier:'foundation'},{id:'targeted',kpId:'k',difficultyTier:'transfer'}];assert.equal(difficulty.rank(list,{mastery:5,preferredIds:['targeted'],rotation:{recentIds:()=>[]}})[0].id,'targeted');});
test('reviewed runtime v4 gives all 86 knowledge points explicit three-tier coverage',()=>{const runtime=loadReviewedRuntime(),catalog=runtime.ManjingoContent;assert.equal(catalog.catalogVersion,'reviewed-v4');assert.equal(catalog.questions.length,503);const teachable=catalog.knowledgePoints.filter(kp=>kp.teachable!==false);assert.equal(teachable.length,86);for(const kp of teachable){const tiers=new Set(catalog.questions.filter(q=>q.kpId===kp.kpId).map(q=>q.difficultyTier).filter(Boolean));assert.ok(tiers.has('foundation'),`${kp.kpId} missing explicit foundation`);assert.ok(tiers.has('application'),`${kp.kpId} missing explicit application`);assert.ok(tiers.has('transfer'),`${kp.kpId} missing explicit transfer`);}for(const kpId of STAGE2_KPS)assert.deepEqual([...new Set(catalog.questions.filter(q=>q.kpId===kpId).map(q=>q.difficultyTier).filter(Boolean))].sort(),['application','foundation','transfer']);});
test('browser loaders and Firestore importer include adaptive and transfer content at the correct boundaries',()=>{const rotation=source('public/question-rotation.js'),catalog=source('public/content-catalog.js'),importer=source('scripts/import_to_firestore.js');for(const suffix of ['01','02','03']){assert.match(rotation,new RegExp(`question-pack-adaptive-${suffix}\\.js`));assert.match(importer,new RegExp(`question-pack-adaptive-${suffix}\\.js`));}assert.match(rotation,/question-difficulty\.js/);assert.match(importer,/question-difficulty\.js/);assert.match(importer,/difficultyTier:question\.difficultyTier\|\|null|difficultyTier: question\.difficultyTier \|\| null/);for(const n of ['03','04','05','06']){assert.match(catalog,new RegExp(`question-pack-transfer-${n}\\.js`));assert.match(importer,new RegExp(`question-pack-transfer-${n}\\.js`));}});
