const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const root=path.join(__dirname,'..');
const source=file=>fs.readFileSync(path.join(root,file),'utf8');
const difficulty=require('../public/question-difficulty.js');
const STAGE2_KPS=['kp_virtual_hu','kp_virtual_qie','kp_virtual_yan','kp_lex_tongjia','kp_lex_intentional','kp_lex_semantic_role'];
function loadReviewedRuntime(){const context={window:{},Map,Set,Array,Object,Number,String,Math};vm.createContext(context);for(const file of ['public/question-pack-02.js','public/question-pack-03.js','public/question-pack-lesson.js','public/question-pack-capacity-01.js','public/question-pack-transfer-01.js','public/question-pack-transfer-03.js','public/question-pack-transfer-04.js','public/question-pack-transfer-05.js','public/question-pack-transfer-06.js','public/content-catalog.js','public/question-pack-adaptive-01.js','public/question-pack-adaptive-02.js','public/question-pack-adaptive-03.js','public/question-difficulty.js'])vm.runInContext(source(file),context,{filename:file});return context.window;}
test('mastery maps to foundation application and transfer tiers',()=>{assert.equal(difficulty.tierForMastery(0),'foundation');assert.equal(difficulty.tierForMastery(39),'foundation');assert.equal(difficulty.tierForMastery(40),'application');assert.equal(difficulty.tierForMastery(74),'application');assert.equal(difficulty.tierForMastery(75),'transfer');assert.equal(difficulty.tierForMastery(100),'transfer');});
test('recent mistakes temporarily step difficulty down while intervention modes override mastery',()=>{assert.equal(difficulty.tierForMastery(82,{lastCorrect:false}),'application');assert.equal(difficulty.tierForMastery(62,{lastCorrect:false}),'foundation');assert.equal(difficulty.tierForMastery(95,{mode:'remedial'}),'foundation');assert.equal(difficulty.tierForMastery(10,{mode:'reteach'}),'transfer');});
test('reviewed runtime gives all 78 knowledge points explicit three-tier coverage',()=>{const runtime=loadReviewedRuntime(),catalog=runtime.ManjingoContent;assert.equal(catalog.catalogVersion,'reviewed-v4');assert.equal(catalog.questions.length,452);const teachable=catalog.knowledgePoints.filter(kp=>kp.teachable!==false);assert.equal(teachable.length,78);for(const kp of teachable){const tiers=new Set(catalog.questions.filter(q=>q.kpId===kp.kpId).map(q=>q.difficultyTier).filter(Boolean));assert.ok(tiers.has('foundation'),`${kp.kpId} missing foundation`);assert.ok(tiers.has('application'),`${kp.kpId} missing application`);assert.ok(tiers.has('transfer'),`${kp.kpId} missing transfer`);}for(const kpId of STAGE2_KPS)assert.deepEqual([...new Set(catalog.questions.filter(q=>q.kpId===kpId).map(q=>q.difficultyTier).filter(Boolean))].sort(),['application','foundation','transfer']);});
test('tier ranking prefers target level while rotation can surface adjacent unseen material',()=>{const list=[{id:'f',kpId:'k',difficultyTier:'foundation'},{id:'a',kpId:'k',difficultyTier:'application'},{id:'t',kpId:'k',difficultyTier:'transfer'}];assert.equal(difficulty.rank(list,{mastery:80,rotation:{recentIds:()=>[]}})[0].id,'t');assert.equal(difficulty.rank(list,{mastery:80,rotation:{recentIds:()=>['t']}})[0].id,'a');});
test('browser loaders and Firestore importer include adaptive and transfer content',()=>{const rotation=source('public/question-rotation.js'),catalog=source('public/content-catalog.js'),importer=source('scripts/import_to_firestore.js');for(const suffix of ['01','02','03']){assert.match(rotation,new RegExp(`question-pack-adaptive-${suffix}\\.js`));assert.match(importer,new RegExp(`question-pack-adaptive-${suffix}\\.js`));}for(const n of ['03','04','05','06']){assert.match(catalog,new RegExp(`question-pack-transfer-${n}\\.js`));assert.match(importer,new RegExp(`question-pack-transfer-${n}\\.js`));}assert.match(importer,/difficultyTier:question\.difficultyTier\|\|null|difficultyTier: question\.difficultyTier \|\| null/);});
