const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const root=path.join(__dirname,'..');
const curriculum=require('../public/curriculum-v1.js');
const metadata=require('../public/question-metadata-v1.js');
function source(file){return fs.readFileSync(path.join(root,file),'utf8')}
function loadCatalog(){const context={window:{},Map,Set,Array,Object,Number,String,Math};vm.createContext(context);for(const file of ['public/question-pack-02.js','public/question-pack-03.js','public/question-pack-lesson.js','public/question-pack-capacity-01.js','public/question-pack-transfer-01.js','public/question-pack-transfer-03.js','public/question-pack-transfer-04.js','public/question-pack-transfer-05.js','public/question-pack-transfer-06.js','public/content-catalog.js'])vm.runInContext(source(file),context,{filename:file});return context.window.ManjingoContent;}
function byId(questions,id){const row=questions.find(q=>q.id===id);assert.ok(row,`missing ${id}`);return row;}
test('all 382 reviewed questions receive a curriculum mode',()=>{const questions=metadata.annotateAll(loadCatalog().questions),valid=new Set(curriculum.skills.map(x=>x.id));assert.equal(questions.length,382);assert.equal(questions.some(q=>q.curriculumMode==='unmapped'),false);for(const q of questions){assert.ok(['core','set-text','advanced'].includes(q.curriculumMode));if(q.curriculumMode==='core')assert.ok(q.skillIds.length>0,`${q.id}: core question has no skill`);for(const id of q.skillIds)assert.ok(valid.has(id),`${q.id}: unknown skill ${id}`);}});
test('pure set-text recall leaves normal core while transferable questions are salvaged',()=>{const q=metadata.annotateAll(loadCatalog().questions);assert.equal(byId(q,'q008').curriculumMode,'set-text');assert.deepEqual(Array.from(byId(q,'p2q041').skillIds),['lex.ancient-modern']);assert.deepEqual(Array.from(byId(q,'p2q071').skillIds),['syn.object-fronting']);});
test('stage 2 questions keep explicit source and skill provenance',()=>{const q=metadata.annotateAll(loadCatalog().questions),checks=[['tr7q001','fw.hu'],['tr7q004','fw.qie'],['tr7q010','fw.yan'],['tr7q016','lex.tongjia'],['tr7q022','lex.intentional'],['tr7q028','lex.semantic-role']];for(const[id,skill]of checks){const row=byId(q,id);assert.deepEqual(Array.from(row.skillIds),[skill]);assert.equal(row.curriculumMode,'core');assert.equal(row.normalCore,true);assert.equal(row.sourceKind,'classical-canon');assert.ok(row.sourceTextId&&row.sourceTextId!=='CROSS');assert.ok(row.sourceSentenceId.startsWith('sentence:'));assert.equal(row.transferLevel,2);}});
test('cross-tagged stage 1 evidence preserves every credited skill',()=>{const q=metadata.annotateAll(loadCatalog().questions);assert.deepEqual(Array.from(byId(q,'tr5q010').skillIds),['trans.function-word','syn.judgment']);assert.deepEqual(Array.from(byId(q,'tr6q001').skillIds),['transfer.single-sentence','lex.context-inference']);});
test('advanced argumentation remains outside normal language core',()=>{const q=metadata.annotateAll(loadCatalog().questions);for(const id of ['lpq055','lpq058','lpq061','p3q045']){const row=byId(q,id);assert.equal(row.curriculumMode,'advanced');assert.equal(row.normalCore,false);}});
test('normal core filter excludes set-text recall without deleting catalog',()=>{const c=loadCatalog(),core=metadata.normalCoreQuestions(c.questions),ids=new Set(core.map(q=>q.id));assert.equal(c.questions.length,382);assert.equal(core.length,291);for(const id of ['q008','lpq053','p2q042'])assert.equal(ids.has(id),false);for(const id of ['tr6q001','tr7q001','tr7q036'])assert.equal(ids.has(id),true);});
test('audit quantifies modes and new transfer sources',()=>{const audit=metadata.audit(loadCatalog().questions);assert.equal(audit.total,382);assert.equal(audit.byMode.core,291);assert.equal(audit.byMode['set-text'],78);assert.equal(audit.byMode.advanced,13);assert.equal(audit.bySourceText.yueyanglou,38);assert.equal(audit.bySourceText.CROSS,45);assert.equal(audit.bySourceText.lunyu,28);assert.equal(audit.bySourceText.quanxue,23);assert.ok(audit.bySourceText.chibifu>=6);assert.ok(audit.bySourceText.zhuzhiwutuiqinshi>=5);});
