const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const root=path.join(__dirname,'..');
const metadata=require('../public/question-metadata-v1.js');
const diversity=require('../public/question-diversity-v1.js');
const skillPlan=require('../public/skill-first-plan.js');
function source(file){return fs.readFileSync(path.join(root,file),'utf8')}
function loadCatalog(){const context={window:{},Map,Set,Array,Object,Number,String,Math,RegExp};vm.createContext(context);for(const file of ['public/question-pack-02.js','public/question-pack-03.js','public/question-pack-lesson.js','public/question-pack-capacity-01.js','public/question-pack-transfer-01.js','public/question-pack-transfer-03.js','public/question-pack-transfer-04.js','public/question-pack-transfer-05.js','public/question-pack-transfer-06.js','public/content-catalog.js'])vm.runInContext(source(file),context,{filename:file});return context.window.ManjingoContent;}
function engine(records={}){const empty={mastery:0,attempts:0,correctCount:0,wrongCount:0,lastCorrect:null,lastAnsweredAt:null,nextReviewAt:null};return{getKnowledge(id){return records[id]?{...empty,...records[id]}:{...empty}},isDue(record){return !!(record&&record.lastAnsweredAt)&&(!record.nextReviewAt||new Date(record.nextReviewAt).getTime()<=Date.now())}};}
const rotation={rank:list=>list.slice(),recentSentenceIds:()=>[]};
function legacyFreshPlan(){return{targetCount:10,items:[{kpId:'kp_yueyang_001',category:'new',priority:3},{kpId:'kp_yueyang_004',category:'new',priority:3},{kpId:'kp_virtual_zhi',category:'new',priority:3},{kpId:'kp_virtual_er',category:'new',priority:3},{kpId:'kp_virtual_yi',category:'new',priority:3},{kpId:'kp_virtual_yu',category:'new',priority:3},{kpId:'kp_virtual_qi',category:'new',priority:3},{kpId:'kp_virtual_ze',category:'new',priority:3},{kpId:'gj_004',category:'new',priority:3},{kpId:'gj_005',category:'new',priority:3}]};}
test('legacy set-text plan is converted into ten unique language skills',()=>{const catalog=loadCatalog(),adapted=skillPlan.adaptPlan(legacyFreshPlan(),catalog.questions,10,{learning:engine()});assert.equal(adapted.skillFirst,true);assert.equal(adapted.items.length,10);assert.equal(new Set(adapted.items.map(x=>x.skillId)).size,10);assert.equal(adapted.items.some(x=>x.skillId===''),false);assert.equal(adapted.items.some(x=>x.kpId==='kp_yueyang_004'),false);});
test('legacy aliases merge into one skill target instead of consuming duplicate slots',()=>{const catalog=loadCatalog(),plan={targetCount:3,items:[{kpId:'kp_virtual_zhi',category:'new',priority:3},{kpId:'kp_p3_zhi',category:'new',priority:3},{kpId:'kp_virtual_er',category:'new',priority:3}]},adapted=skillPlan.adaptPlan(plan,catalog.questions,3,{learning:engine()});assert.equal(adapted.items.length,3);assert.equal(adapted.items.filter(x=>x.skillId==='fw.zhi').length,1);assert.ok(adapted.items.some(x=>x.skillId==='fw.er'));assert.equal(new Set(adapted.items.map(x=>x.skillId)).size,3);});
test('mastery evidence from one legacy alias changes the shared skill category',()=>{const catalog=loadCatalog(),plan={targetCount:1,items:[{kpId:'kp_virtual_zhi',category:'new',priority:3}]},weak=engine({kp_p3_zhi:{attempts:3,mastery:35,lastCorrect:false,lastAnsweredAt:'2026-09-11T10:00:00Z',nextReviewAt:'2099-01-01T00:00:00Z'}}),adapted=skillPlan.adaptPlan(plan,catalog.questions,1,{learning:weak});assert.equal(adapted.items[0].skillId,'fw.zhi');assert.equal(adapted.items[0].category,'weak');});
test('stable mastery on an alias prevents the same skill being treated as fresh',()=>{const catalog=loadCatalog(),plan={targetCount:1,items:[{kpId:'kp_virtual_zhi',category:'new',priority:3}]},stable=engine({kp_p3_zhi:{attempts:8,mastery:92,lastCorrect:true,lastAnsweredAt:'2026-09-11T10:00:00Z',nextReviewAt:'2099-01-01T00:00:00Z'}}),adapted=skillPlan.adaptPlan(plan,catalog.questions,1,{learning:stable});assert.equal(adapted.items.length,1);assert.notEqual(adapted.items[0].skillId,'fw.zhi');assert.equal(adapted.items[0].category,'new');});
test('learner-facing selection emits only normal-core questions and one question per planned skill',()=>{const catalog=loadCatalog(),selected=skillPlan.selectQuestionsForPlan(legacyFreshPlan(),catalog.questions,10,{learning:engine(),rotation,diversity});assert.equal(selected.length,10);assert.equal(new Set(selected.map(x=>x.skillId)).size,10);for(const q of selected)assert.equal(metadata.annotate(q).normalCore,true,`${q.id} must stay in normal core`);assert.equal(selected.some(q=>new Set(['q008','lpq052','lpq053','lpq054','p2q042']).has(q.id)),false);});
test('skill-first selection keeps misconception remediation exact when the question belongs to that skill',()=>{const catalog=loadCatalog(),plan={targetCount:1,items:[{kpId:'kp_p3_yi',category:'weak',priority:2,misconceptionQuestionIds:['p3q009']}]},selected=skillPlan.selectQuestionsForPlan(plan,catalog.questions,1,{learning:engine({kp_p3_yi:{attempts:2,mastery:30,lastCorrect:false,lastAnsweredAt:'2026-09-11T10:00:00Z',nextReviewAt:'2099-01-01T00:00:00Z'}}),rotation,diversity});assert.equal(selected[0].id,'p3q009');assert.equal(selected[0].skillId,'fw.yi');assert.equal(selected[0].misconceptionReview,true);});
test('fresh skill order interleaves domains instead of walking legacy article order',()=>{const catalog=loadCatalog(),pools=skillPlan.poolsFor(catalog.questions),ordered=skillPlan.orderedSkillIds(pools).slice(0,6),domains=ordered.map(id=>require('../public/curriculum-v1.js').skill(id).domain);assert.ok(new Set(domains).size>=4,`expected broad domain mix, got ${domains.join(',')}`);});
function assertSkillPool(skillIds,planItems){const catalog=loadCatalog(),pools=skillPlan.poolsFor(catalog.questions);for(const skillId of skillIds){const pool=pools.get(skillId);assert.ok(pool&&pool.length>=6,`${skillId} missing from skill-first pool`);assert.equal(pool.every(q=>metadata.annotate(q).normalCore),true,`${skillId} pool must stay normal-core`);}const selected=skillPlan.selectQuestionsForPlan({targetCount:planItems.length,items:planItems},catalog.questions,planItems.length,{learning:engine(),rotation,diversity}),selectedIds=new Set(selected.map(q=>q.skillId));for(const id of skillIds)assert.ok(selectedIds.has(id),`${id} not scheduled`);}
test('stage 1 reading foundations enter the normal skill-first scheduling pool',()=>assertSkillPool(['read.sentence-core','read.context-clues','read.logical-relation','syn.negative-patterns'],[{kpId:'kp_read_sentence_core',category:'new',priority:3},{kpId:'kp_read_context_clues',category:'new',priority:3},{kpId:'kp_read_logical_relation',category:'new',priority:3},{kpId:'kp_syn_negative_patterns',category:'new',priority:3}]));
test('stage 1 translation foundations enter the normal skill-first scheduling pool',()=>assertSkillPool(['syn.interrogative-patterns','trans.function-word','trans.supplement','trans.ancient-modern'],[{kpId:'kp_syn_interrogative_patterns',category:'new',priority:3},{kpId:'kp_trans_function_word',category:'new',priority:3},{kpId:'kp_trans_supplement',category:'new',priority:3},{kpId:'kp_trans_ancient_modern',category:'new',priority:3}]));
test('dedicated KPs keep their migration skill identity when evidence is cross-tagged',()=>{const catalog=loadCatalog();for(const[kpId,skillId]of [['kp_trans_function_word','trans.function-word'],['kp_trans_supplement','trans.supplement'],['kp_trans_ancient_modern','trans.ancient-modern'],['kp_transfer_single_sentence','transfer.single-sentence']]){const adapted=skillPlan.adaptPlan({targetCount:1,items:[{kpId,category:'new',priority:3}]},catalog.questions,1,{learning:engine()});assert.equal(adapted.items[0].skillId,skillId,`${kpId} must keep ${skillId} as primary scheduling identity`);}});
test('single-sentence transfer enters the normal skill-first scheduling pool',()=>assertSkillPool(['transfer.single-sentence'],[{kpId:'kp_transfer_single_sentence',category:'new',priority:3}]));
test('second stage 2 native KPs enter skill-first scheduling with direct skill identity',()=>assertSkillPool(['syn.attributive-postpose','syn.fixed-patterns','read.parallel-inference'],[{kpId:'kp_syn_attributive_postpose',category:'new',priority:3},{kpId:'kp_syn_fixed_patterns',category:'new',priority:3},{kpId:'kp_read_parallel_inference',category:'new',priority:3}]));
test('stage 2 closeout native KPs enter skill-first scheduling with direct skill identity',()=>assertSkillPool(['read.actor-tracking','read.unknown-word-tolerance','trans.fluency','transfer.sentence-pair','transfer.micro-passage'],[{kpId:'kp_read_actor_tracking',category:'new',priority:3},{kpId:'kp_read_unknown_word_tolerance',category:'new',priority:3},{kpId:'kp_trans_fluency',category:'new',priority:3},{kpId:'kp_transfer_sentence_pair',category:'new',priority:3},{kpId:'kp_transfer_micro_passage',category:'new',priority:3}]));
test('question rotation browser loader installs skill-first layer before adaptive packs',()=>{const s=fs.readFileSync(path.join(root,'public/question-rotation.js'),'utf8'),skillIndex=s.indexOf('./skill-first-plan.js'),adaptiveIndex=s.indexOf('./question-pack-adaptive-01.js');assert.ok(skillIndex>=0&&adaptiveIndex>skillIndex);});
