const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const skillSource=fs.readFileSync(path.join(__dirname,'..','public','skill-mastery-v1.js'),'utf8');
const plan=require('../public/skill-first-plan.js');
const accountSync=require('../public/account-sync.js');

function storage(initial={}){const map=new Map(Object.entries(initial));return{map,getItem:key=>map.has(key)?map.get(key):null,setItem:(key,value)=>map.set(key,String(value)),removeItem:key=>map.delete(key)}}
function loadSkill(initial={}){const localStorage=storage(initial),context={window:{},localStorage,JSON,Date,Math,Number,String,Object,Array,Map,Set,console};vm.createContext(context);vm.runInContext(skillSource,context);return{api:context.window.ManjingoSkillMasteryV1,localStorage}}
function engine(records={}){return{getKnowledge(id){return records[id]||{mastery:0,attempts:0,correctCount:0,wrongCount:0,lastCorrect:null,lastAnsweredAt:null,nextReviewAt:null}},isDue(record){return !record.nextReviewAt||new Date(record.nextReviewAt).getTime()<=Date.now()}}}

test('legacy KP aliases project into one weighted skill mastery record',()=>{const{api}=loadSkill(),learning=engine({a:{mastery:90,attempts:8,correctCount:7,wrongCount:1,lastCorrect:true,lastAnsweredAt:'2026-09-10T12:00:00Z',nextReviewAt:'2026-09-20T12:00:00Z'},b:{mastery:20,attempts:2,correctCount:0,wrongCount:2,lastCorrect:false,lastAnsweredAt:'2026-09-09T12:00:00Z',nextReviewAt:'2026-09-11T12:00:00Z'}}),record=api.projectLegacy('fw.zhi',{engine:learning,kpIds:['a','b']});assert.equal(record.mastery,76);assert.equal(record.attempts,10);assert.equal(record.correctCount,7);assert.equal(record.wrongCount,3);assert.equal(record.lastCorrect,true);assert.equal(record.lastAnsweredAt,'2026-09-10T12:00:00Z');assert.equal(record.nextReviewAt,'2026-09-11T12:00:00Z');assert.deepEqual(Array.from(record.kpIds),['a','b']);assert.equal(record.source,'legacy-projection')});

test('skill projection is persisted without rewriting legacy knowledge',()=>{const initial={totalXp:40,knowledge:{a:{mastery:70,attempts:3,lastCorrect:true,lastAnsweredAt:'2026-09-10T12:00:00Z',nextReviewAt:'2026-09-15T12:00:00Z'}}},store=storage({manjingo_progress_cache:JSON.stringify(initial)}),context={window:{},localStorage:store,JSON,Date,Math,Number,String,Object,Array,Map,Set,console};vm.createContext(context);vm.runInContext(skillSource,context);const api=context.window.ManjingoSkillMasteryV1,record=api.getSkillMastery('fw.er',{engine:engine(initial.knowledge),kpIds:['a']}),saved=JSON.parse(store.getItem('manjingo_progress_cache'));assert.equal(record.mastery,70);assert.equal(saved.totalXp,40);assert.equal(saved.knowledge.a.mastery,70);assert.equal(saved.skillMastery['fw.er'].mastery,70);assert.equal(saved.skillMastery['fw.er'].projectionVersion,'skill-mastery-projection-v1')});

test('newer stored skill evidence wins over an older legacy projection',()=>{const initial={skillMastery:{'fw.yi':{skillId:'fw.yi',mastery:88,attempts:5,lastCorrect:true,lastAnsweredAt:'2026-09-11T12:00:00Z',nextReviewAt:'2026-09-20T12:00:00Z',kpIds:['a'],source:'skill-native'}},knowledge:{a:{mastery:30,attempts:9,lastCorrect:false,lastAnsweredAt:'2026-09-10T12:00:00Z',nextReviewAt:'2026-09-11T12:00:00Z'}}},store=storage({manjingo_progress_cache:JSON.stringify(initial)}),context={window:{},localStorage:store,JSON,Date,Math,Number,String,Object,Array,Map,Set,console};vm.createContext(context);vm.runInContext(skillSource,context);const record=context.window.ManjingoSkillMasteryV1.getSkillMastery('fw.yi',{engine:engine(initial.knowledge),kpIds:['a']});assert.equal(record.mastery,88);assert.equal(record.source,'skill-native');assert.equal(record.lastAnsweredAt,'2026-09-11T12:00:00Z')});

test('equal-time native skill beats a legacy projection with more historical KP attempts',()=>{const time='2026-09-11T12:00:00Z',initial={skillMastery:{'fw.yi':{skillId:'fw.yi',mastery:88,attempts:1,lastCorrect:true,lastAnsweredAt:time,nextReviewAt:'2026-09-20T12:00:00Z',kpIds:['a'],source:'server-native-v1'}},knowledge:{a:{mastery:30,attempts:9,lastCorrect:false,lastAnsweredAt:time,nextReviewAt:'2026-09-20T12:00:00Z'}}},store=storage({manjingo_progress_cache:JSON.stringify(initial)}),context={window:{},localStorage:store,JSON,Date,Math,Number,String,Object,Array,Map,Set,console};vm.createContext(context);vm.runInContext(skillSource,context);const record=context.window.ManjingoSkillMasteryV1.getSkillMastery('fw.yi',{engine:engine(initial.knowledge),kpIds:['a']});assert.equal(record.mastery,88);assert.equal(record.source,'server-native-v1');assert.equal(record.attempts,1)});

test('account sync keeps the newer skill mastery snapshot across devices',()=>{const local={skillMastery:{'fw.yu':{skillId:'fw.yu',mastery:40,attempts:2,lastAnsweredAt:'2026-09-09T12:00:00Z'}},knowledge:{},conceptMastery:{},practiceHistory:[]},remote={skillMastery:{'fw.yu':{skillId:'fw.yu',mastery:75,attempts:4,lastAnsweredAt:'2026-09-10T12:00:00Z'},'fw.qi':{skillId:'fw.qi',mastery:55,attempts:3,lastAnsweredAt:'2026-09-10T11:00:00Z'}},knowledge:{},conceptMastery:{},practiceHistory:[]},merged=accountSync.mergeLearningState(local,remote);assert.equal(merged.skillMastery['fw.yu'].mastery,75);assert.equal(merged.skillMastery['fw.qi'].mastery,55)});

test('account sync uses evidence time before attempt count for skill records',()=>{const local={skillMastery:{'fw.yu':{skillId:'fw.yu',mastery:35,attempts:20,lastAnsweredAt:'2026-09-09T12:00:00Z',source:'legacy-projection'}}},remote={skillMastery:{'fw.yu':{skillId:'fw.yu',mastery:82,attempts:1,lastAnsweredAt:'2026-09-10T12:00:00Z',source:'server-native-v1'}}},merged=accountSync.mergeLearningState(local,remote);assert.equal(merged.skillMastery['fw.yu'].mastery,82);assert.equal(merged.skillMastery['fw.yu'].source,'server-native-v1')});

test('skill-first state prefers a skill record over conflicting legacy KP records',()=>{const learning=engine({legacy:{mastery:20,attempts:5,lastCorrect:false,lastAnsweredAt:'2026-09-10T12:00:00Z',nextReviewAt:'2099-01-01T00:00:00Z'}}),skillApi={getSkillMastery(){return{skillId:'fw.zhi',mastery:92,attempts:8,lastCorrect:true,lastAnsweredAt:'2026-09-11T12:00:00Z',nextReviewAt:'2099-01-01T00:00:00Z'}}};assert.equal(plan.skillState(['legacy'],learning,'fw.zhi',skillApi),'stable');assert.equal(plan.skillState(['legacy'],learning,'fw.zhi',{getSkillMastery(){return null}}),'weak')});

test('browser loader installs skill mastery before skill-first planning',()=>{const source=fs.readFileSync(path.join(__dirname,'..','public','question-rotation.js'),'utf8'),masteryIndex=source.indexOf('./skill-mastery-v1.js'),planIndex=source.indexOf('./skill-first-plan.js');assert.ok(masteryIndex>=0);assert.ok(planIndex>masteryIndex)});