const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const root=path.join(__dirname,'..');
const curriculum=require('../public/curriculum-v1.js');
const metadata=require('../public/question-metadata-v1.js');
function read(file){return fs.readFileSync(path.join(root,file),'utf8')}
function loadCatalog(){const context={window:{},Map,Set,Array,Object,Number,String,Math,RegExp};vm.createContext(context);for(const file of ['public/question-pack-02.js','public/question-pack-03.js','public/question-pack-lesson.js','public/question-pack-capacity-01.js','public/question-pack-transfer-01.js','public/question-pack-transfer-03.js','public/question-pack-transfer-04.js','public/question-pack-transfer-05.js','public/question-pack-transfer-06.js','public/content-catalog.js'])vm.runInContext(read(file),context,{filename:file});return context.window.ManjingoContent;}
function coverage(){const questions=metadata.annotateAll(loadCatalog().questions).filter(q=>q.normalCore),policy=curriculum.qualityPolicy;return curriculum.coreSkills().map(skill=>{const matched=questions.filter(q=>q.skillIds.includes(skill.id)),namedSources=new Set(matched.map(q=>String(q.sourceTextId||'')).filter(x=>x&&x!=='CROSS'&&x!=='UNKNOWN')),unseen=matched.filter(q=>q.sourceKind!=='set-text').length,gaps=[];if(matched.length<policy.minimumQuestionsPerCoreSkill)gaps.push(`questions:${matched.length}/${policy.minimumQuestionsPerCoreSkill}`);if(namedSources.size<policy.minimumSourceTextsPerCoreSkill)gaps.push(`sources:${namedSources.size}/${policy.minimumSourceTextsPerCoreSkill}`);if(unseen<policy.minimumUnseenOrNonSetTextQuestions)gaps.push(`unseen:${unseen}/${policy.minimumUnseenOrNonSetTextQuestions}`);return{id:skill.id,stage:skill.stage,questions:matched.length,sources:namedSources.size,unseen,gaps};});}
function assertCleared(ids){const byId=new Map(coverage().map(x=>[x.id,x]));for(const id of ids){const row=byId.get(id);assert.ok(row);assert.deepEqual(row.gaps,[],`${id}: ${row.gaps.join(', ')}`);assert.ok(row.questions>=6);assert.ok(row.sources>=3);assert.ok(row.unseen>=2);}}
test('skill coverage audit reports 11 remaining stage 2 deficits after first batch',()=>{const report=coverage(),core=metadata.normalCoreQuestions(loadCatalog().questions),deficits=report.filter(x=>x.gaps.length);assert.equal(core.length,291);assert.equal(deficits.length,11);assert.equal(deficits.some(x=>x.stage===1),false);console.log('SKILL_COVERAGE_AUDIT='+JSON.stringify({totalCoreQuestions:core.length,deficitSkills:deficits.length,deficits}));});
test('stage 1 remains fully above the quality floor',()=>{assertCleared(curriculum.coreSkills().filter(x=>x.stage===1).map(x=>x.id));});
test('first stage 2 batch clears three function words and three lexical skills',()=>assertCleared(['fw.hu','fw.qie','fw.yan','lex.tongjia','lex.intentional','lex.semantic-role']));
test('remaining partial stage 2 skills stay visible until their source diversity is fixed',()=>{const byId=new Map(coverage().map(x=>[x.id,x]));for(const id of ['lex.word-class-shift','syn.adverbial-postpose','syn.ellipsis-object'])assert.ok(byId.get(id).gaps.some(x=>x.startsWith('sources:')),`${id} should still expose source debt`);});
