const fs=require('node:fs');
const path=require('node:path');
const root=path.join(__dirname,'..');
const read=file=>fs.readFileSync(path.join(root,file),'utf8');
const fail=message=>{console.error('✖ mascot determined P4: '+message);process.exitCode=1};
const ok=message=>console.log('✔ mascot determined P4: '+message);
const manifest=JSON.parse(read('public/mascot/manifest.json'));
const state=id=>manifest.states.find(item=>item.id===id);
const determined=state('determined'),thinking=state('thinking'),neutral=state('neutral');
if(!determined)fail('manifest is missing the determined state');
if(!thinking)fail('manifest is missing the thinking state');
if(!neutral)fail('manifest is missing the neutral state');
if(process.exitCode)process.exit(process.exitCode);
if(determined.asset!=='./mascot/moling-determined.svg')fail('determined asset path changed');
if(determined.productionPriority!==4)fail('determined must remain P4');
if(thinking.artStatus!=='production')fail('P4 assumes thinking P3 is already production');
if(neutral.artStatus!=='baseline-approved'&&neutral.artStatus!=='production')fail('neutral must remain the approved runtime anchor');
const svg=read('public/mascot/moling-determined.svg');
const neutralSvg=read('public/mascot/moling-neutral.svg');
const thinkingSvg=read('public/mascot/moling-thinking.svg');
if(!/viewBox="0 0 215 320"/.test(svg))fail('determined must keep the 215×320 viewBox');
if(/<text\b/i.test(svg))fail('determined SVG must not embed text');
if(!/<title\b[^>]*>[^<]*(堅定|determined)/i.test(svg))fail('determined should retain an accessible title');
if(!/<desc\b/i.test(svg))fail('determined should retain an accessible description');
const referencesBaseline=/mascot-moling\.svg/.test(svg);
const aggressiveMarkup=/(id|class)=["'][^"']*(angry|fight|battle|rage|fire|flame|lightning|weapon|trophy|medal|pressure|warning|countdown)[^"']*["']/i.test(svg);
const safeLanguage=/(安定|韌性|準備|determined|resilien|ready)/i.test(svg);
const embedded=svg.match(/data:image\/webp;base64,([^"']+)/i);
const webp=embedded?Buffer.from(embedded[1],'base64'):null;
const valid=webp&&webp.subarray(0,4).toString('ascii')==='RIFF'&&webp.subarray(8,12).toString('ascii')==='WEBP';
const vp8xAlpha=valid&&webp.subarray(12,16).toString('ascii')==='VP8X'&&(webp[20]&0x10)!==0;
const alphaChunk=valid&&webp.includes(Buffer.from('ALPH'));
if(determined.artStatus==='placeholder-treatment'){
  if(!referencesBaseline)fail('placeholder-treatment should reference the approved baseline');
  ok('placeholder treatment remains baseline-derived');
}else if(determined.artStatus==='candidate'||determined.artStatus==='production'){
  if(referencesBaseline)fail(determined.artStatus+' determined must be independent from mascot-moling.svg');
  if(svg===neutralSvg||svg===thinkingSvg)fail('determined artwork must be a genuinely distinct pose');
  if(svg.length<30000)fail('determined SVG is suspiciously small for embedded 3D artwork');
  if(!/<image\b/i.test(svg)||!embedded)fail('determined should contain embedded transparent 3D artwork');
  if(!valid)fail('determined data URI must decode to a valid WebP');
  if(!vp8xAlpha&&!alphaChunk)fail('determined WebP must contain a real alpha channel, not a flattened checkerboard');
  if(aggressiveMarkup)fail('determined contains aggressive or pressure visual markup');
  if(!safeLanguage)fail('determined description should preserve calm resilient intent');
  ok(determined.artStatus+' determined artwork is independent and structurally reviewable');
  ok('no aggressive or pressure visual markup detected');
}else fail('unexpected determined artStatus: '+determined.artStatus);
if(process.exitCode)process.exit(process.exitCode);
ok('P4 structural and emotional-safety gate passed');
